### ISSUE TITLE
Bugfix: wrong file reference in error

### ISSUE THREAD

**Issue by Lorenzobattistela** [HigherOrderCO/monobook#11]
This issue refers to [this](https://github.com/VictorTaelin/agda-cli) repo, and is registered here to be easier to track. It integrates with the workflow for compiling / running the book.

Bug report:
When using `agda-cli check A.agda`, if there is an error in other file (B.agda), the reported error message shows the wrong file content.

Reproducing: 
```agda
module A where

open import B

data AType : Set where
  AConstructor : MyType → AType
exampleA : AType
exampleA = AConstructor (id A)
```

```agda
module B where

data MyType : Set where
  A : MyType

id : MyType → MyType
id A = b
```

![image](https://github.com/user-attachments/assets/b957b8e3-64bf-43a5-8c55-64f8dba94e74)

It shows the line on the A module when it should be the one in B module.

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
