### ISSUE TITLE
Improve Agda-JS code generation: Uncurried functions and tagged constructors

### ISSUE THREAD

**Issue by kings177** [HigherOrderCO/monobook#17]
Enhance the agda to javascript compiler to optimize function calls and improve data representation

## 1. Uncurry Global Functions

Implement uncurrying for global functions to allow direct application when saturated.

Uncurrying can significantly improve performance for fully applied functions by reducing the number of function calls and closures created.

### Objectives	
- Identify global functions in the Agda AST
- Implement an uncurrying mechanism for these functions
- Compile each global function to two versions: curried and uncurried
- Ensure that uncurried functions are applied directly when all arguments are provided

### Implementation Details
- Generate two versions of each global function:
    - Curried version: `foo`
    - Uncurried version: `foo$`
- Use the curried version by default in the generated code
- In cases where the function is saturated in the generated code, use the uncurried version

### Example
```js
// Curried version (default)
const foo = x => y => z => x + y + z;

// Uncurried version 
const foo$ = (x, y, z) => x + y + z;
```

```js
// Usage in unsaturated contexts (curried)
const partial = foo(a)(b);

// Usage in saturated contexts (uncurried)
const result = foo$(a, b, c);
```

## 2. Update Constructor Compilation

Modify the compilation of constructors to use a more structured representation and update the corresponding elimination functions. This will make the pattern matching more efficient and improve readability of the generated code.

### Objectives

- Compile constructors to the format `{$: "CtrName", field0, field1, ...}`
- Update elimination functions to work with this new constructor representation

### Example
```js
const Cons = (x, xs) => ({$: "Cons", field0: x, field1: xs}); 
const elimList = (nil, cons, xs) => 
    xs.$ === 'Nil' ? nil : cons(xs.field0)(xs.field1);
``` 

## Considerations
- Ensure that partial application still works correctly after implementing uncurrying
- Handle higher-order functions and functions with dependent types carefully in the uncurrying process
- Update all existing elimination functions to work with the new constructor representation

**Comment by developedby** [comment]
Do we plan on keeping a fork of Agda with compiler improvements? I don't know how easy it is to upstream there.

**Comment by developedby** [comment]
Compilation of function calls is handled here https://github.com/agda/agda/blob/26ef5bcba940898ca861ea7a46304e3a30dea77b/src/full/Agda/Compiler/JS/Compiler.hs#L555.
Note how they already handle partial applications via eta-expansion.

This is mainly for better looking generated code right? I feel like a js compiler would already optimize a simple thing like this.

Lambdas are added for the funtion arguments here https://github.com/agda/agda/blob/26ef5bcba940898ca861ea7a46304e3a30dea77b/src/full/Agda/Compiler/JS/Compiler.hs#L446.

Also, do we want to uncurry lambdas as well?
For example:
```agda
silly-ex a b = \x -> (x a b)
```

**Comment by VictorTaelin** [comment]
@mietek will be responsible for this on the Agda repo
