### ISSUE TITLE
Koder Style guide

### ISSUE THREAD

**Issue by SergioBonatto** [HigherOrderCO/monobook#82]
# Defining the Style Guide
- Taelin explained the desired pattern,
- We watched the video of his explanation,
- Now we need to write the style guide, providing examples of what is correct and what should be avoided.

# Examples
### Let usage
```hs
pad-length : Bits → Bits → Pair Bits Bits
pad-length a b = do
  let len-a   = length a
  let len-b   = length b
  let trg-len = max len-a len-b
  pad-zeros trg-len a , pad-zeros trg-len b
``` 

### If-then-else ident
```hs
exists : String -> I Bool
exists path = do
  file-exists <- is-file path
  if file-exists
    then pure True
    else is-directory path
```

# Deliverables

- [ ] Document with koder's style guide

**Comment by Sipher** [comment]
instances aren't following a concistent naming scheme. ex:
```
instance
  Show-Int : Show Int

instance
  OrdInt : Ord Int
  ```
  This has to be adjusted. please add to the guideline and update all faulty places
